In [47]:
import numpy as np
a = np.array([1,2,3,4])
print(a)
b = np.arange(1,11)
print(b)
c = np.arange(1,10,5)
print(c)
d = np.linspace(1,10,5)
print(d)
b = b.reshape(5,2)
print(b)
#np.zeros(50)
np.eye(2)

[1 2 3 4]
[ 1  2  3  4  5  6  7  8  9 10]
[1 6]
[  1.     3.25   5.5    7.75  10.  ]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


array([[ 1.,  0.],
       [ 0.,  1.]])

In [37]:
import numpy as np
import pandas as pd
s = pd.Series([10,20,30,40],index=[1,2,3,4])
print(s)
print(s[[2,3]])
print(np.sqrt(s))

1    10
2    20
3    30
4    40
dtype: int64
2    20
3    30
dtype: int64
1    3.162278
2    4.472136
3    5.477226
4    6.324555
dtype: float64


In [43]:
data = pd.DataFrame({'price':[95, 25, 85, 41, 78],
                     'ticker':['AXP', 'CSCO', 'DIS', 'MSFT', 'WMT'],
                     'company':['American Express', 'Cisco', 'Walt Disney','Microsoft', 'Walmart']})
print(data)
#data['company']
data.ix[1]

            company  price ticker
0  American Express     95    AXP
1             Cisco     25   CSCO
2       Walt Disney     85    DIS
3         Microsoft     41   MSFT
4           Walmart     78    WMT


company    Cisco
price         25
ticker      CSCO
Name: 1, dtype: object

In [44]:
years = [90, 91, 92, 93, 94, 95]
print('-------------Firm 1------------')
f1 = {90:8, 91:9, 92:7, 93:8, 94:9, 95:11}
firm1 = pd.Series(f1,index=years)
print(firm1)
print('-------------Firm 2------------')
f2 = {90:14,92:9, 93:13, 94:5}
firm2 = pd.Series(f2,index=years)
print(firm2)
print('-------------Firm 3------------')
f3 = {93:10, 94:12, 95: 13}
firm3 = pd.Series(f3,index=years)
print(firm3)
print('-------------Create empty dataframe------------')
df1 = pd.DataFrame(columns=['Firm1','Firm2','Firm3'],index=years)    # Convert the 3 series to a DataFrame with 'years' as Index
print(df1)
print('-------------Populate the dataframe------------')
df1.Firm1 = firm1
df1.Firm2 = firm2
df1.Firm3 = firm3
print(df1)

-------------Firm 1------------
90     8
91     9
92     7
93     8
94     9
95    11
dtype: int64
-------------Firm 2------------
90    14.0
91     NaN
92     9.0
93    13.0
94     5.0
95     NaN
dtype: float64
-------------Firm 3------------
90     NaN
91     NaN
92     NaN
93    10.0
94    12.0
95    13.0
dtype: float64
-------------Create empty dataframe------------
   Firm1 Firm2 Firm3
90   NaN   NaN   NaN
91   NaN   NaN   NaN
92   NaN   NaN   NaN
93   NaN   NaN   NaN
94   NaN   NaN   NaN
95   NaN   NaN   NaN
-------------Populate the dataframe------------
    Firm1  Firm2  Firm3
90      8   14.0    NaN
91      9    NaN    NaN
92      7    9.0    NaN
93      8   13.0   10.0
94      9    5.0   12.0
95     11    NaN   13.0


In [48]:
dataframe = pd.DataFrame(np.random.rand(3,3),columns=['one','two','three'])  # Create array of 3*3 dimensionality using standard normally distributed random vales
dataframe

one       two     three
0  0.538588  0.498810  0.670010
1  0.662960  0.500276  0.088885
2  0.308323  0.592499  0.012416